#!/usr/bin/env bash
name="file"
version="5.45"
description="Identify a files format by scanning binary data for patterns"
source=("http://ftp.astron.com/pub/file/file-${version}.tar.gz")
depends=""
display=":$(ls /tmp/.X11-unix/* | sed 's#/tmp/.X11-unix/X##' | head -1)"
user=$(who | grep "(${display})" | awk '{print $1}')
# Display adı
# Display kullanıcısı
ROOT="/home/$user/distro"
ROOTBUILDDIR="$ROOT/build"
# Derleme dizini
BUILDDIR="$ROOT/build/build-${name}-${version}" # Alt dizin
DESTDIR="$ROOT/rootfs"
# Yükleme dizini
PACKAGEDIR=$(pwd)
# Paket dizini
SOURCEDIR="$ROOT/build/${name}-${version}" # Kaynak dizini
initsetup(){
mkdir -p $ROOTBUILDDIR #derleme dizini yoksa oluşturuluyor
rm -rf $ROOTBUILDDIR/* #içeriği temizleniyor
cd $ROOTBUILDDIR #dizinine geçiyoruz
wget ${source}
dowloadfile=$(ls|head -1)
filetype=$(file -b --extension $dowloadfile|cut -d'/' -f1)
if [ "${filetype}" == "???" ]; then unzip ${dowloadfile}; else tar -xvf ${dowloadfile};fi
director=$(find ./* -maxdepth 0 -type d)
directorname=$(basename ${director})
if [ "${directorname}" != "${name}-${version}" ]; then mv $directorname ${name}-${version};fi
mkdir -p $BUILDDIR&&mkdir -p $DESTDIR&&cd $SOURCEDIR
}
setup(){
opts=(
--prefix=/usr
--libdir=/usr/lib64
--enable-static
--enable-elf
--enable-elf-core
)
./configure ${opts[@]} \
$(use_opt zlib --enable-zlib --disable-zlib) \
$(use_opt lzma --enable-xzlib --disable-xzlib) \
$(use_opt bzip2 --enable-bzlib --disable-bzlib) \
$(use_opt seccomp --enable-libseccomp --disable-libseccomp)
}
build(){
make
}
package(){
make install DESTDIR=$DESTDIR
${DESTDIR}/sbin/ldconfig -r ${DESTDIR}
# sistem guncelleniyor
}
initsetup
# initsetup fonksiyonunu çalıştırır ve kaynak dosyayı indirir
setup
# setup fonksiyonu çalışır ve derleme öncesi kaynak dosyaların ayalanması sağlanır.
build
# build fonksiyonu çalışır ve kaynak dosyaları derlenir.
package
# package fonksiyonu çalışır, yükleme öncesi ayarlamalar yapılır ve yüklenir.
